---
# Inspired from: https://github.com/bachya/smart-home/blob/master/esphome/.topgreener_tgwf115pqm_smart_plug.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
    name: "${name} Power Button"
    on_press:
      - switch.toggle: relay

  - platform: status
    name: "${friendly_name} Status"

esphome:
  name: "${name}"
  platform: ESP8266
  board: esp8285

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current:
      name: "${friendly_name} Current"
      accuracy_decimals: 3
      filters:
        - calibrate_linear:
            - 0.0 -> 0.013
            - 0.09994 -> 0.077
            - 0.10139 -> 0.077
            - 0.10284 -> 0.077
        - lambda: if (x < 0.01) return 0; else return (x - 0.013);
    power:
      name: "${friendly_name} Power"
      accuracy_decimals: 0
      filters:
        - calibrate_linear:
            - 0.0 -> 0.5
            - 7.24053 -> 5.3
            - 8.27489 -> 5.3
        - lambda: if (x < 2) return 0; else return (x - 0.5);
    voltage:
      name: "${friendly_name} Voltage"
      accuracy_decimals: 1
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 128.88396 -> 119.8
            - 128.96568 -> 119.8
            - 129.04739 -> 119.9
    update_interval: 10s

status_led:
  pin:
    number: GPIO1
    inverted: true

switch:
  - platform: gpio
    id: led
    pin: GPIO13
    inverted: true

  - platform: gpio
    name: "${friendly_name}"
    pin: GPIO14
    id: relay
    on_turn_on:
      - switch.turn_on: led
    on_turn_off:
      - switch.turn_off: led
