---
platform: gpio
pin:
  number: D2
name: ${name} Motion
id: rclw_input_sensor
# on_state:
#   then:
#     if:
#       condition:
#         binary_sensor.is_on: rclw_input_sensor
#       then:
#         - switch.turn_on: activity_indicator
#         - delay: 500ms
#         - switch.turn_off: activity_indicator
#         - delay: 500ms
