version: "3"

services:
  esphome:
    image: esphome/esphome:latest
    #devices:
    #  - "/dev/ttyUSB0:/dev/ttyUSB0"
    #  - "/dev/bus/usb:/dev/bus/usb"
    # - "/dev/ttyS3:/dev/ttyUSB0"

    privileged: true
    container_name: esphome
    volumes:
      - ./config:/config:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ESPHOME_DASHBOARD_USE_PING=true
    ports:
      - 6152:6052
      - 6123:6123
    network_mode: host
    restart: unless-stopped