<<: !include common/common.yaml

substitutions:
  name: multisensor_garage
  friendly_name: Garage Multisensor
  update_interval: 1min
  ip: 192.168.30.32

esphome:
  name: $name
  platform: ESP8266
  board: nodemcuv2

i2c:
  sda: GPIO4
  scl: GPIO5

# Enable logging
logger:

sensor:
  -  !include common/sensor/uptime.config.yaml
  -  !include common/sensor/wifi_signal.config.yaml
  -  !include common/sensor/bme280.config.yaml
  -  !include common/sensor/dewpoint.yaml
  
  
binary_sensor:
  -  !include common/binary_sensor/connection_status.config.yaml
  -  !include common/binary_sensor/motion.yaml
