<<: !include common/common.yaml

substitutions:
  name: unit1_hallway_lights
  friendly_name: Kitchen Hallway Lights
  icon: "mdi:chart-multiline"
  update_interval: 5min
  ip: 192.168.30.70
    
<<: !include common/device/gosund_sw6.yaml