<<: !include common/common.yaml

substitutions:
  name: unit1_lights_kitchen_cabinets
  friendly_name: Unit1 Lights Kitchen Cabinets
  icon: "mdi:chart-multiline"
  update_interval: 5min
  ip: 192.168.30.24
    
<<: !include common/device/gosund_sw6.yaml
