<<: !include common/common.yaml

substitutions:
  name: unit1_socket_livingroom_couch
  friendly_name: Unit2 Socket Livingroom Couch
  icon: "mdi:chart-multiline"
  update_interval: 5min
  ip: 192.168.30.22
    
logger:

<<: !include common/device/tgwf115pqm_smart_plug.yaml