<<: !include common/common.yaml

substitutions:
  name: outlet-bedroom2
  friendly_name: Unit2 Socket Bedroom
  icon: "mdi:chart-multiline"
  update_interval: 5min
  ip: 192.168.30.20

logger:

<<: !include common/device/tgwf115pqm_smart_plug.yaml