<<: !include common/common.yaml

substitutions:
  name: lights-staircase
  id: lights_staircase
  friendly_name: Staircase Lights
  icon: "mdi:chart-multiline"
  update_interval: 5min
  ip: 192.168.30.21

logger:

mdns:

<<: !include common/device/gosund_sw6.yaml
