<<: !include common/common.yaml

substitutions:
  name: outlet-livingroom2-couch
  friendly_name: Unit2 Socket Livingroom Couch
  icon: "mdi:chart-multiline"
  update_interval: 5min
  ip: 192.168.30.19
    
logger:

<<: !include common/device/tgwf115pqm_smart_plug.yaml