<<: !include common/common.yaml

substitutions:
  name: outlet-backroom-couch
  friendly_name: Unit1 Socket Livingroom Couch
  icon: "mdi:chart-multiline"
  update_interval: 5min
  ip: 192.168.30.22
    
logger:

<<: !include common/device/tgwf115pqm_smart_plug.yaml