---
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: high # Without this, the devices seem to get rather warm.
  manual_ip:
    static_ip: ${ip}
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
  ap:
    ssid: "ESPHome-Fallback"
    password: !secret wifi_fallback_password

#mdns:

captive_portal:
